spring.application.name=DemoApplication


# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Lab7demo
spring.datasource.username=postgres
spring.datasource.password=516712

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect